services:
    _defaults:
        autowire: true
        autoconfigure: true
    MajesticDev\MilsimIdCard\:
        resource: '../src/'
        exclude: ['../src/Entity/', '../src/Enum/', '../src/DTO/', '../src/MilsimIdCardPlugin.php', '../src/Discord/']
    MajesticDev\MilsimIdCard\Service\PhotoStorage:
        arguments:
            $projectDir: '%kernel.project_dir%'
